default: &default
  adapter: postgresql
  encoding: unicode
  password: postgres
  username: postgres
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: michael_bizarre_adventure_development
  host: localhost
  port: 5432

test:
  <<: *default
  database: michael_bizarre_adventure_test
  host: localhost
  port: 5432

production:
  <<: *default
  database: michael_bizarre_adventure_production
  username: michael_bizarre_adventure
  password: <%= ENV["MICHAEL_BIZARRE_ADVENTURE_DATABASE_PASSWORD"] %>
